.TH C_MRK1 1 "July 2024" "Version 1.0" "C_MRK1 Manual"
.SH NAME
c_mrk1 \- brief description
.SH SYNOPSIS
.B c_mrk1
[\fIoptions\fR]
.SH DESCRIPTION
.B c_mrk1
is a detailed description of your program or script. This section explains what your program does and how to use it.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help message.
.TP
.B \-v, \-\-version
Display version information.
.TP
.B \-o, \-\-option \fIargument\fR
This option requires a specific argument. Describe the argument in detail here.

.SH EXAMPLES
Here are some examples of how to use the program:
.P
.nf
\&$ c_mrk1 -o example_argument
.fi

.SH FILES
This section lists the files that the program uses or creates.

.SH AUTHOR
Author's name and contact information.

.SH SEE ALSO
References to related commands or documentation.